### ISSUE TITLE
求助：Qwen-7B微调报错 assert all((i.dtype in [torch.float16, torch.bfloat16] for i in (q, k, v))) 

### ISSUE THREAD

**Issue by yixing** [yangjianxin1/Firefly#105]
$ torchrun --nproc_per_node=1 train_qlora.py --train_args_file train_args/qlora/qwen-7b-sft-qlora.json

# 启动后模型加载正常，报如下错误：

2023-08-13 12:25:42.698 | INFO     | component.dataset:__init__:12 - Loading data: ./data/dummy_data.jsonl
2023-08-13 12:25:42.698 | INFO     | component.dataset:__init__:15 - there are 33 data in dataset
2023-08-13 12:25:42.704 | INFO     | __main__:main:204 - *** starting training ***
  0%|                                                                                                                                         | 0/3 [00:00<?, ?it/s]`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`...
Traceback (most recent call last):
  File "/home/work/workspace/Firefly/train_qlora.py", line 217, in <module>
    main()
  File "/home/work/workspace/Firefly/train_qlora.py", line 205, in main
    train_result = trainer.train()
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/work/workspace/Firefly/component/trainer.py", line 72, in compute_loss
    return self.loss_func(model, inputs, self.args, return_outputs)
  File "/home/work/workspace/Firefly/component/loss.py", line 35, in __call__
    outputs = model(input_ids=input_ids, attention_mask=attention_mask, return_dict=True)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/3d036e335a1ff45432253e03b654e71eb68c2d4e/modeling_qwen.py", line 894, in forward
    transformer_outputs = self.transformer(
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/3d036e335a1ff45432253e03b654e71eb68c2d4e/modeling_qwen.py", line 722, in forward
    outputs = torch.utils.checkpoint.checkpoint(
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/work/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/3d036e335a1ff45432253e03b654e71eb68c2d4e/modeling_qwen.py", line 718, in custom_forward
    return module(*inputs, use_cache, output_attentions)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/3d036e335a1ff45432253e03b654e71eb68c2d4e/modeling_qwen.py", line 511, in forward
    attn_outputs = self.attn(
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/3d036e335a1ff45432253e03b654e71eb68c2d4e/modeling_qwen.py", line 429, in forward
    context_layer = self.core_attention_flash(q, k, v)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/work/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/3d036e335a1ff45432253e03b654e71eb68c2d4e/modeling_qwen.py", line 130, in forward
    assert all((i.dtype in [torch.float16, torch.bfloat16] for i in (q, k, v)))
AssertionError
  0%|                                                                                                                                         | 0/3 [00:00<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2957) of binary: /home/work/workspace/.venv/bin/python
Traceback (most recent call last):
  File "/home/work/workspace/.venv/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/work/workspace/.venv/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
============================================================
train_qlora.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------

**Comment by RayWang-iat** [comment]
请问大佬解决了吗。我也是同样的错

**Comment by samsha1971** [comment]
我也是同样的错

**Comment by lale314** [comment]
卸载 flashattn

**Comment by samsha1971** [comment]
> 卸载 flashattn

果然如此，感谢！

**Comment by yechong316** [comment]
> > 卸载 flashattn
> 
> 感谢帮忙解答，我训练qwen的时候，确实没有使用flash attention。
----我也是按照上述方法训练，删除flash-attention之后，抛出下文错误，如何解决
Traceback (most recent call last):
  File "/workspace/Firefly/train.py", line 6, in <module>
    from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
  File "/usr/local/lib/python3.10/dist-packages/peft/__init__.py", line 22, in <module>
    from .auto import (
  File "/usr/local/lib/python3.10/dist-packages/peft/auto.py", line 33, in <module>
    from .config import PeftConfig
  File "/usr/local/lib/python3.10/dist-packages/peft/config.py", line 24, in <module>
    from .utils import CONFIG_NAME, PeftType, TaskType
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/__init__.py", line 22, in <module>
    from .other import (
  File "/usr/local/lib/python3.10/dist-packages/peft/utils/other.py", line 20, in <module>
    import accelerate
  File "/usr/local/lib/python3.10/dist-packages/accelerate/__init__.py", line 3, in <module>
    from .accelerator import Accelerator
  File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 35, in <module>
    from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
  File "/usr/local/lib/python3.10/dist-packages/accelerate/checkpointing.py", line 24, in <module>
    from .utils import (
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/__init__.py", line 153, in <module>
    from .launch import (
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/launch.py", line 33, in <module>
    from ..utils.other import is_port_in_use, merge_dicts
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/other.py", line 36, in <module>
    from .transformer_engine import convert_model
  File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/transformer_engine.py", line 21, in <module>
    import transformer_engine.pytorch as te
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/__init__.py", line 11, in <module>
    from .attention import DotProductAttention
  File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 56, in <module>
    _flash_attn_version = packaging.version.Version(version("flash-attn"))
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 996, in version
    return distribution(distribution_name).version
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 969, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for flash-attn

**Comment by yangjianxin1** [comment]
用qlora训练吗，训练的配置文件贴一下&nbsp;


杨坚新
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年5月6日(星期一) 中午11:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [yangjianxin1/Firefly] 求助：Qwen-7B微调报错 assert all((i.dtype in [torch.float16, torch.bfloat16] for i in (q, k, v)))  (Issue #105)














   
卸载 flashattn
  
感谢帮忙解答，我训练qwen的时候，确实没有使用flash attention。
 ----我也是按照上述方法训练，删除flash-attention之后，抛出下文错误，如何解决
 Traceback (most recent call last):
 File "/workspace/Firefly/train.py", line 6, in 
 from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
 File "/usr/local/lib/python3.10/dist-packages/peft/init.py", line 22, in 
 from .auto import (
 File "/usr/local/lib/python3.10/dist-packages/peft/auto.py", line 33, in 
 from .config import PeftConfig
 File "/usr/local/lib/python3.10/dist-packages/peft/config.py", line 24, in 
 from .utils import CONFIG_NAME, PeftType, TaskType
 File "/usr/local/lib/python3.10/dist-packages/peft/utils/init.py", line 22, in 
 from .other import (
 File "/usr/local/lib/python3.10/dist-packages/peft/utils/other.py", line 20, in 
 import accelerate
 File "/usr/local/lib/python3.10/dist-packages/accelerate/init.py", line 3, in 
 from .accelerator import Accelerator
 File "/usr/local/lib/python3.10/dist-packages/accelerate/accelerator.py", line 35, in 
 from .checkpointing import load_accelerator_state, load_custom_state, save_accelerator_state, save_custom_state
 File "/usr/local/lib/python3.10/dist-packages/accelerate/checkpointing.py", line 24, in 
 from .utils import (
 File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/init.py", line 153, in 
 from .launch import (
 File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/launch.py", line 33, in 
 from ..utils.other import is_port_in_use, merge_dicts
 File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/other.py", line 36, in 
 from .transformer_engine import convert_model
 File "/usr/local/lib/python3.10/dist-packages/accelerate/utils/transformer_engine.py", line 21, in 
 import transformer_engine.pytorch as te
 File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/init.py", line 11, in 
 from .attention import DotProductAttention
 File "/usr/local/lib/python3.10/dist-packages/transformer_engine/pytorch/attention.py", line 56, in 
 _flash_attn_version = packaging.version.Version(version("flash-attn"))
 File "/usr/lib/python3.10/importlib/metadata/init.py", line 996, in version
 return distribution(distribution_name).version
 File "/usr/lib/python3.10/importlib/metadata/init.py", line 969, in distribution
 return Distribution.from_name(distribution_name)
 File "/usr/lib/python3.10/importlib/metadata/init.py", line 548, in from_name
 raise PackageNotFoundError(name)
 importlib.metadata.PackageNotFoundError: No package metadata was found for flash-attn
