### ISSUE TITLE
全参微调chatglm2-6b报错 ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.

### ISSUE THREAD

**Issue by Modas-Li** [yangjianxin1/Firefly#114]
server1: Traceback (most recent call last):
server1:   File "train.py", line 130, in <module>
server1:     main()
server1:   File "train.py", line 115, in main
server1:     trainer = init_components(args, training_args)
server1:   File "train.py", line 53, in init_components
server1:     model = AutoModelForCausalLM.from_pretrained(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
server1:     raise ValueError(
server1: ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
server1: Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by kingdomad** [comment]
老哥怎么解决的，直接改成AutoModel吗

**Comment by lvzii** [comment]
老哥，解决没有。改成AutoModel训完，保存的模型和原来模型参数一样，没有变化。

**Comment by cy565025164** [comment]
用QWen微调后测试同样的错误
