### ISSUE TITLE
加载chatglm2-6b报错：NotImplementedError: Cannot copy out of meta tensor; no data!

### ISSUE THREAD

**Issue by Modas-Li** [yangjianxin1/Firefly#116]
Traceback (most recent call last):
server1:   File "train.py", line 130, in <module>
server1:     main()
server1:   File "train.py", line 115, in main
server1:     trainer = init_components(args, training_args)
server1:   File "train.py", line 53, in init_components
server1:     model = AutoModelForCausalLM.from_pretrained(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
server1:     return model_class.from_pretrained(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
server1:     model = cls(config, *model_args, **model_kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
server1:     f(module, *args, **kwargs)
server1:   File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 854, in __init__
server1:     self.transformer = ChatGLMModel(config, empty_init=empty_init, device=device)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
server1:     f(module, *args, **kwargs)
server1:   File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 741, in __init__
server1:     self.embedding = init_method(Embedding, config, **init_kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/torch/nn/utils/init.py", line 52, in skip_init
server1:     return module_cls(*args, **kwargs).to_empty(device=final_device)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
server1:     f(module, *args, **kwargs)
server1:   File "/root/.cache/huggingface/modules/transformers_modules/chatglm2-6b/modeling_chatglm.py", line 711, in __init__
server1:     self.word_embeddings = nn.Embedding(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 392, in wrapper
server1:     self._post_init_method(module)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 839, in _post_init_method
server1:     param.partition()
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 966, in partition
server1:     self._partition(param_list, has_been_updated=has_been_updated)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1104, in _partition
server1:     self._partition_param(param, has_been_updated=has_been_updated)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
server1:     ret_val = func(*args, **kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1186, in _partition_param
server1:     param.ds_tensor.copy_(src_tensor)
server1: NotImplementedError: Cannot copy out of meta tensor; no data!

**Comment by Essence9999** [comment]
升级transformer版本
