### ISSUE TITLE
合并权重后的模型无法加载

### ISSUE THREAD

**Issue by xusysh** [yangjianxin1/Firefly#118]
使用`scripts/merge_lora.py`合并后，无法使用`script/chat/single_chat.py`加载
报错如下
```
root@autodl-container-d31d468cfc-2be7ed09:~/autodl-tmp/Firefly/script/chat# python single_chat.py 
Loading /root/autodl-tmp/firefly-baichuan-13b-qlora-sft-merge requires to execute some code in that repo, you can inspect the content of the repository at https://hf.co//root/autodl-tmp/firefly-baichuan-13b-qlora-sft-merge. You can dismiss this prompt by passing `trust_remote_code=True`.
Do you accept? [y/N] y
Could not locate the configuration_baichuan.py inside /root/autodl-tmp/firefly-baichuan-13b-qlora-sft-merge.
Traceback (most recent call last):
  File "single_chat.py", line 69, in <module>
    main()
  File "single_chat.py", line 23, in main
    model = AutoModelForCausalLM.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 456, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/models/auto/configuration_auto.py", line 953, in from_pretrained
    config_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 431, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/dynamic_module_utils.py", line 247, in get_cached_module_file
    resolved_module_file = cached_file(
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: /root/autodl-tmp/firefly-baichuan-13b-qlora-sft-merge does not appear to have a file named configuration_baichuan.py. Checkout 'https://huggingface.co//root/autodl-tmp/firefly-baichuan-13b-qlora-sft-merge/None' for available files.
```
合并后的目录，和原baichuan-13b-base相比少了一些文件
![image](https://github.com/yangjianxin1/Firefly/assets/32706918/65c15aa4-ee56-4e86-afe6-7d3a4dd21d61)
尝试拷入这些缺失文件后，报这个错
![image](https://github.com/yangjianxin1/Firefly/assets/32706918/df3862c3-9148-41fd-89dd-e824f46e0385)

**Comment by ljdavns** [comment]
量化加载就可以了

**Comment by Data2Me** [comment]
请问这个问题解决了吗，我遇到了相同的问题

**Comment by 22zhangqian** [comment]
期待一个答案 我也遇到这个问题
