### ISSUE TITLE
RuntimeError: output tensor must have the same type as input tensor when training qwen-7b

### ISSUE THREAD

**Issue by Modas-Li** [yangjianxin1/Firefly#127]
server1: Traceback (most recent call last):
server1:   File "train.py", line 130, in <module>
server1:     main()
server1:   File "train.py", line 115, in main
server1:     trainer = init_components(args, training_args)
server1:   File "train.py", line 53, in init_components
server1:     model = AutoModelForCausalLM.from_pretrained(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
server1:     return model_class.from_pretrained(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2881, in from_pretrained
server1:     ) = cls._load_pretrained_model(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3246, in _load_pretrained_model
server1:     error_msgs += _load_state_dict_into_model(model_to_load, state_dict, start_prefix)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 550, in _load_state_dict_into_model
server1:     load(model_to_load, state_dict, prefix=start_prefix)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
server1:     load(child, state_dict, prefix + name + ".")
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
server1:     load(child, state_dict, prefix + name + ".")
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]
server1:     load(child, state_dict, prefix + name + ".")
server1:   [Previous line repeated 2 more times]
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 540, in load
Loading checkpoint shards:   0%|          | 0/8 [00:00<?, ?it/s]
server1:     with deepspeed.zero.GatheredParameters(params_to_gather, modifier_rank=0):
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1667, in __enter__
server1: Traceback (most recent call last):
server1:   File "train.py", line 130, in <module>
server1: Traceback (most recent call last):
server1:   File "train.py", line 130, in <module>
server1:     main()
server1:   File "train.py", line 115, in main
server1:     self.params[0].all_gather(param_list=self.params)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 890, in all_gather
server1:     main()
server1:   File "train.py", line 115, in main
server1:     trainer = init_components(args, training_args)
server1:   File "train.py", line 53, in init_components
server1:     trainer = init_components(args, training_args)
server1:   File "train.py", line 53, in init_components
server1:     return self._all_gather(param_list, async_op=async_op, hierarchy=hierarchy)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
server1:     model = AutoModelForCausalLM.from_pretrained(
server1:     model = AutoModelForCausalLM.from_pretrained(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
server1: ret_val = func(*args, **kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1092, in _all_gather
server1:     return model_class.from_pretrained(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2881, in from_pretrained
server1:     ret_value = self._allgather_params_coalesced(all_gather_list, hierarchy)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1315, in _allgather_params_coalesced
server1:     return model_class.from_pretrained(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2881, in from_pretrained
server1:     h = dist.all_gather_into_tensor(allgather_params[param_idx],
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 116, in log_wrapper
server1:     return func(*args, **kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 297, in all_gather_into_tensor
server1:     return cdb.all_gather_into_tensor(output_tensor=output_tensor, input_tensor=tensor, group=group, async_op=async_op)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 136, in all_gather_into_tensor
server1:     return self.all_gather_function(output_tensor=output_tensor,
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2358, in all_gather_into_tensor
server1:     ) = cls._load_pretrained_model(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3246, in _load_pretrained_model
server1:     ) = cls._load_pretrained_model(
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 3246, in _load_pretrained_model
server1:     work = group._allgather_base(output_tensor, input_tensor)
server1: RuntimeError: output tensor must have the same type as input tensor
server1:     error_msgs += _load_state_dict_into_model(model_to_load, state_dict, start_prefix)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 550, in _load_state_dict_into_model
server1:     error_msgs += _load_state_dict_into_model(model_to_load, state_dict, start_prefix)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 550, in _load_state_dict_into_model
server1:     load(model_to_load, state_dict, prefix=start_prefix)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
server1:     load(model_to_load, state_dict, prefix=start_prefix)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
server1:     load(child, state_dict, prefix + name + ".")
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
server1:     load(child, state_dict, prefix + name + ".")
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
server1:     load(child, state_dict, prefix + name + ".")
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
server1:     load(child, state_dict, prefix + name + ".")
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 548, in load
server1:     load(child, state_dict, prefix + name + ".")
server1: load(child, state_dict, prefix + name + ".")
server1:   [Previous line repeated 2 more times]
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 540, in load
server1:   [Previous line repeated 2 more times]
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/transformers/modeling_utils.py", line 540, in load
server1:     with deepspeed.zero.GatheredParameters(params_to_gather, modifier_rank=0):
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1667, in __enter__
server1:     with deepspeed.zero.GatheredParameters(params_to_gather, modifier_rank=0):
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1667, in __enter__
server1:     self.params[0].all_gather(param_list=self.params)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 890, in all_gather
server1:     self.params[0].all_gather(param_list=self.params)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 890, in all_gather
server1:     return self._all_gather(param_list, async_op=async_op, hierarchy=hierarchy)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
server1:     return self._all_gather(param_list, async_op=async_op, hierarchy=hierarchy)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/utils/nvtx.py", line 15, in wrapped_fn
server1:     ret_val = func(*args, **kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1092, in _all_gather
server1:     ret_val = func(*args, **kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1092, in _all_gather
server1:     ret_value = self._allgather_params_coalesced(all_gather_list, hierarchy)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1315, in _allgather_params_coalesced
server1:     ret_value = self._allgather_params_coalesced(all_gather_list, hierarchy)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 1315, in _allgather_params_coalesced
server1:     h = dist.all_gather_into_tensor(allgather_params[param_idx],
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 116, in log_wrapper
server1:     h = dist.all_gather_into_tensor(allgather_params[param_idx],
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 116, in log_wrapper
server1:     return func(*args, **kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 297, in all_gather_into_tensor
server1:     return func(*args, **kwargs)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/comm.py", line 297, in all_gather_into_tensor
server1:     return cdb.all_gather_into_tensor(output_tensor=output_tensor, input_tensor=tensor, group=group, async_op=async_op)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 136, in all_gather_into_tensor
server1:     return self.all_gather_function(output_tensor=output_tensor,
server1:       File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2358, in all_gather_into_tensor
server1: return cdb.all_gather_into_tensor(output_tensor=output_tensor, input_tensor=tensor, group=group, async_op=async_op)
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/deepspeed/comm/torch.py", line 136, in all_gather_into_tensor
server1:     return self.all_gather_function(output_tensor=output_tensor,
server1:   File "/data/anaconda3/envs/firefly/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 2358, in all_gather_into_tensor
server1:     work = group._allgather_base(output_tensor, input_tensor)
server1: RuntimeError: output tensor must have the same type as input tensor
server1:     work = group._allgather_base(output_tensor, input_tensor)
server1: RuntimeError: output tensor must have the same type as input tensor

**Comment by zeng9t** [comment]
same question

**Comment by cy565025164** [comment]
same issue

**Comment by sharejing** [comment]
same issue

**Comment by Modas-Li** [comment]
Solution:
update model files to the latest and alter config(sft.json, ds_config.json) fp16 to bf16,make sure your GPUs are more than A100(40g)*4.

**Comment by wangjiwu** [comment]
Solution:

first  add this to  ds_z3_config.json
  "bf16": {
    "enabled": "auto"
},
then 
add     "bf16": true   to  sft.json 
and  delete   "fp16"
