### ISSUE TITLE
ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided []

### ISSUE THREAD

**Issue by zizhegao** [yangjianxin1/Firefly#158]
不管是Lora还是全参数微调（chatglm2），到3-400个step的时候，就会报这个错，详细报错如下：
raceback (most recent call last):
  File "Firefly/train.py", line 142, in <module>
    main()
  File "Firefly/train.py", line 129, in main
    train_result = trainer.train()
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1553, in train
    return inner_training_loop(
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/transformers/trainer.py", line 1813, in _inner_training_loop
    for step, inputs in enumerate(epoch_iterator):
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/accelerate/data_loader.py", line 394, in __iter__
    next_batch = next(dataloader_iter)
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/gpfsdata/home/zizhe/Firefly/component/dataset.py", line 79, in __getitem__
    utterances_ids = self.tokenizer(utterances, add_special_tokens=False).input_ids
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2602, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2688, in _call_one
    return self.batch_encode_plus(
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2879, in batch_encode_plus
    return self._batch_encode_plus(
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 744, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 816, in _batch_prepare_for_model
    batch_outputs = self.pad(
  File "/gpfsdata/home/zizhe/.local/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3018, in pad
    raise ValueError(
ValueError: You should supply an encoding or a list of encodings to this method that includes input_ids, but you provided []

**Comment by zizhegao** [comment]
已解决~

**Comment by zizhegao** [comment]
训练集中有空值，去掉即可

hjqqqq-bot ***@***.***> 于2023年10月30日周一 19:31写道：
