### ISSUE TITLE
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

### ISSUE THREAD

**Issue by JOY-SWang** [yangjianxin1/Firefly#171]
`Loading checkpoint shards:   0%|                                                                             | 0/2 [00:00<?, ?it/s]WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 899505 closing signal SIGTERM                                WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 899506 closing signal SIGTERM                                WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 899507 closing signal SIGTERM                                WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 899508 closing signal SIGTERM                                WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 899510 closing signal SIGTERM                                ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 4 (pid: 899509) of binary: /home/xdx/miniconda3/envs/baichuanft/bin/python                                                                                                      Traceback (most recent call last):                                                                                                   File "/home/xdx/miniconda3/envs/baichuanft/bin/torchrun", line 33, in <module>                                                       sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())                                                     File "/home/xdx/miniconda3/envs/baichuanft/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper                                                                                                              return f(*args, **kwargs)                                                                                                        File "/home/xdx/miniconda3/envs/baichuanft/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main                  run(args)                                                                                                                        File "/home/xdx/miniconda3/envs/baichuanft/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run                   elastic_launch(                                                                                                                  File "/home/xdx/miniconda3/envs/baichuanft/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__     return launch_agent(self._config, self._entrypoint, list(args))                                                                  File "/home/xdx/miniconda3/envs/baichuanft/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent                                                                                                                                    raise ChildFailedError(                                                                                                        torch.distributed.elastic.multiprocessing.errors.ChildFailedError:                                                                 =======================================================                                                                            train_qlora.py FAILED                                                                                                              -------------------------------------------------------                                                                            Failures:                                                                                                                            <NO_OTHER_FAILURES>                                                                                                              -------------------------------------------------------                                                                            Root Cause (first observed failure):                                                                                               [0]:                                                                                                                                 time      : 2023-10-20_17:41:33                                                                                                    host      : debian                                                                                                                 rank      : 4 (local_rank: 4)                                                                                                      exitcode  : -9 (pid: 899509)                                                                                                       error_file: <N/A>                                                                                                                  traceback : Signal 9 (SIGKILL) received by PID 899509  `
how to sole this problem?怎么解决555

**Comment by lonngxiang** [comment]
一样的问题；torchrun qlora微调时
 
![image](https://github.com/yangjianxin1/Firefly/assets/40717349/9e576ab8-afdb-42af-9a31-beeef4bb6554)
