### ISSUE TITLE
微调Qwen-7B，推理报错RuntimeError: FlashAttention only supports Ampere GPUs or newer.

### ISSUE THREAD

**Issue by dashilu1573** [yangjianxin1/Firefly#177]
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.
Traceback (most recent call last):
  File "/home/luyafei/Firefly/script/chat/single_chat.py", line 74, in <module>
    main()
  File "/home/luyafei/Firefly/script/chat/single_chat.py", line 61, in main
    outputs = model.generate(
  File "/home/luyafei/.cache/huggingface/modules/transformers_modules/Qwen-7B-qlora-sft-merge/modeling_qwen.py", line 1318, in generate
    return super().generate(
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/transformers/generation/utils.py", line 1572, in generate
    return self.sample(
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/transformers/generation/utils.py", line 2619, in sample
    outputs = self(
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/luyafei/.cache/huggingface/modules/transformers_modules/Qwen-7B-qlora-sft-merge/modeling_qwen.py", line 1108, in forward
    transformer_outputs = self.transformer(
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/luyafei/.cache/huggingface/modules/transformers_modules/Qwen-7B-qlora-sft-merge/modeling_qwen.py", line 938, in forward
    outputs = block(
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/luyafei/.cache/huggingface/modules/transformers_modules/Qwen-7B-qlora-sft-merge/modeling_qwen.py", line 639, in forward
    attn_outputs = self.attn(
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/accelerate/hooks.py", line 164, in new_forward
    output = module._old_forward(*args, **kwargs)
  File "/home/luyafei/.cache/huggingface/modules/transformers_modules/Qwen-7B-qlora-sft-merge/modeling_qwen.py", line 546, in forward
    context_layer = self.core_attention_flash(q, k, v, attention_mask=attention_mask)
  File "/home/ec2-user/anaconda3/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/luyafei/.cache/huggingface/modules/transformers_modules/Qwen-7B-qlora-sft-merge/modeling_qwen.py", line 213, in forward
    output = flash_attn_unpadded_func(
  File "/home/ec2-user/anaconda3/envs/llm-py3.9-tf2.11/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 906, in flash_attn_varlen_func
    return FlashAttnVarlenFunc.apply(
  File "/home/ec2-user/anaconda3/envs/llm-py3.9-tf2.11/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 496, in forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = _flash_attn_varlen_forward(
  File "/home/ec2-user/anaconda3/envs/llm-py3.9-tf2.11/lib/python3.9/site-packages/flash_attn/flash_attn_interface.py", line 79, in _flash_attn_varlen_forward
    out, q, k, v, out_padded, softmax_lse, S_dmask, rng_state = flash_attn_cuda.varlen_fwd(
RuntimeError: FlashAttention only supports Ampere GPUs or newer.

**Comment by EricLeeaaaaa** [comment]
你用的什么显卡？如果是游戏卡必须是30系以上
