### ISSUE TITLE
训练qwen -14B-base 报错，chat 正常

### ISSUE THREAD

**Issue by hopeforus** [yangjianxin1/Firefly#195]
2023-12-30 09:32:35.529 | INFO     | component.dataset:__init__:317 - there are 1074551 data in dataset
2023-12-30 09:32:35.545 | INFO     | __main__:main:221 - *** starting training ***
  0%|                                                                                                                                                                                          | 0/89546 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/hope/work/Firefly/train_qlora.py", line 235, in <module>
    main()
  File "/home/hope/work/Firefly/train_qlora.py", line 224, in main
    train_result = trainer.train()
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/transformers/trainer.py", line 1645, in train
    return inner_training_loop(
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/transformers/trainer.py", line 1938, in _inner_training_loop
    tr_loss_step = self.training_step(model, inputs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/transformers/trainer.py", line 2759, in training_step
    loss = self.compute_loss(model, inputs)
  File "/home/hope/work/Firefly/component/trainer.py", line 73, in compute_loss
    loss = super().compute_loss(model, inputs, return_outputs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/transformers/trainer.py", line 2784, in compute_loss
    outputs = model(**inputs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/utils/operations.py", line 581, in forward
    return model_forward(*args, **kwargs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/utils/operations.py", line 569, in __call__
    return convert_to_fp32(self.model_forward(*args, **kwargs))
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 14, in decorate_autocast
    return func(*args, **kwargs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/peft/peft_model.py", line 922, in forward
    return self.base_model(
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hope/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 1108, in forward
    transformer_outputs = self.transformer(
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hope/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 926, in forward
    outputs = torch.utils.checkpoint.checkpoint(
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 249, in checkpoint
    return CheckpointFunction.apply(function, preserve, *args)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/utils/checkpoint.py", line 107, in forward
    outputs = run_function(*args)
  File "/home/hope/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 922, in custom_forward
    return module(*inputs, use_cache, output_attentions)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hope/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 639, in forward
    attn_outputs = self.attn(
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/hooks.py", line 165, in new_forward
    output = old_forward(*args, **kwargs)
  File "/home/hope/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 546, in forward
    context_layer = self.core_attention_flash(q, k, v, attention_mask=attention_mask)
  File "/home/hope/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hope/.cache/huggingface/modules/transformers_modules/Qwen-14B/modeling_qwen.py", line 174, in forward
    assert all((i.dtype in [torch.float16, torch.bfloat16] for i in (q, k, v)))
AssertionError

**Comment by Mrwenjunru** [comment]
我也base模型微调遇到这个问题，请问问题解决了吗？且增量预训练后合并adapter的base模型在生成文本不会停止，这是否正常？
