### ISSUE TITLE
deepspeed安装报错

### ISSUE THREAD

**Issue by TC10127** [yangjianxin1/Firefly#255]
(unsloth_env) D:\work\Firefly-master\Firefly-master>pip install deepspeed==0.9.5
Collecting deepspeed==0.9.5
  Using cached deepspeed-0.9.5.tar.gz (809 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [15 lines of output]
      test.c
      LINK : fatal error LNK1181: 无法打开输入文件“aio.lib”
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-zaj2fo7g\deepspeed_c6b12afd0dc34f24995fde18f2ea2bfe\setup.py", line 163, in <module>
          abort(f"Unable to pre-compile {op_name}")
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-zaj2fo7g\deepspeed_c6b12afd0dc34f24995fde18f2ea2bfe\setup.py", line 51, in abort
          assert False, msg
      AssertionError: Unable to pre-compile async_io
      DS_BUILD_OPS=1
       [WARNING]  async_io requires the dev libaio .so object and headers but these were not found.
       [WARNING]  If libaio is already installed (perhaps from source), try setting the CFLAGS and LDFLAGS environment variables to where it can be found.
       [WARNING]  One can disable async_io with DS_BUILD_AIO=0
       [ERROR]  Unable to pre-compile async_io
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.       

pytorch=2.3，cuda=12.1

**Comment by Parasolation** [comment]
试试用conda安装呢
