### ISSUE TITLE
请问我运行“python train.py --train_args_file train_args/sft/qlora/baichuan-7b-sft-qlora.json”指令，为什么报一下错误呀？

### ISSUE THREAD

**Issue by lh5533223** [yangjianxin1/Firefly#283]

**Comment by lh5533223** [comment]
bin E:\software\anaconda\install\envs\llmExtraction\lib\site-packages\bitsandbytes\libbitsandbytes_cuda116.dll Traceback (most recent call last):   File "E:\lh\llm_open_triplet_extraction-main\Firefly\train.py", line 439, in <module>     main()   File "E:\lh\llm_open_triplet_extraction-main\Firefly\train.py", line 422, in main     args, training_args = setup_everything()   File "E:\lh\llm_open_triplet_extraction-main\Firefly\train.py", line 52, in setup_everything     args, training_args = parser.parse_json_file(json_file=train_args_file)   File "E:\software\anaconda\install\envs\llmExtraction\lib\site-packages\transformers\hf_argparser.py", line 397, in parse_json_file     data = json.loads(open_json_file.read())   File "E:\software\anaconda\install\envs\llmExtraction\lib\json\__init__.py", line 346, in loads     return _default_decoder.decode(s)   File "E:\software\anaconda\install\envs\llmExtraction\lib\json\decoder.py", line 337, in decode     obj, end = self.raw_decode(s, idx=_w(s, 0).end())   File "E:\software\anaconda\install\envs\llmExtraction\lib\json\decoder.py", line 353, in raw_decode     obj, end = self.scan_once(s, idx) json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 3 column 1 (char 60)
