### ISSUE TITLE
Token indices sequence length is longer than the specified maximum sequence length for this model (4868 > 4096). Running this sequence through the model will result in indexing errors

### ISSUE THREAD

**Issue by FrozenZero** [yangjianxin1/Firefly#71]
单机8卡的情况下，微调百川Baichuan-13B， train_args/qlora/baichuan-13b-sft-qlora.json如下
<details><summary>Details</summary>
<p>

{
    "output_dir": "output/firefly-baichuan-13b",
    "model_name_or_path": "../../models/baichuan-inc/Baichuan-13B-Base",
    "train_file": "./data/moss-003-sft-data.jsonl",
    "num_train_epochs": 1,
    "per_device_train_batch_size": 6,
    "gradient_accumulation_steps": 2,
    "learning_rate": 1e-4,
    "max_seq_length": 900,
    "logging_steps": 300,
    "save_steps": 500,
    "save_total_limit": 1,
    "lr_scheduler_type": "constant_with_warmup",
    "warmup_steps": 3000,
    "lora_rank": 64,
    "lora_alpha": 16,
    "lora_dropout": 0.05,
    "gradient_checkpointing": true,
    "disable_tqdm": false,
    "optim": "paged_adamw_32bit",
    "seed": 42,
    "fp16": true,
    "report_to": "tensorboard",
    "dataloader_num_workers": 5,
    "save_strategy": "steps",
    "weight_decay": 0,
    "max_grad_norm": 0.3,
    "remove_unused_columns": false
}

</p>
</details> 

训练：
```
torchrun --nproc_per_node=8 train_qlora.py --train_args_file train_args/qlora/baichuan-13b-sft-qlora.json
``` 
训练时候遇到问题：
Token indices sequence length is longer than the specified maximum sequence length for this model (4484 > 4096). Running this sequence through the model will result in indexing errors
WARNING:torch.distributed.elastic.agent.server.api:Received 1 death signal, shutting down workers
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3932380 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3932381 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3932382 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3932383 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3932384 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3932385 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3932386 closing signal SIGHUP
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3932387 closing signal SIGHUP
Traceback (most recent call last):
  File "/home/anaconda3/envs/fireflyft/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 237, in launch_agent
    result = agent.run()
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/elastic/metrics/api.py", line 129, in wrapper
    result = f(*args, **kwargs)
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 709, in run
    result = self._invoke_run(role)
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/elastic/agent/server/api.py", line 850, in _invoke_run
    time.sleep(monitor_interval)
  File "/home/anaconda3/envs/fireflyft/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/api.py", line 62, in _terminate_process_handler
    raise SignalException(f"Process {os.getpid()} got signal: {sigval}", sigval=sigval)
torch.distributed.elastic.multiprocessing.api.SignalException: Process 3932313 got signal: 1

但是我看Firefly-master/component/dataset.py文件中有对token进行截取
```python
        input_ids = input_ids[:self.max_seq_length]
        target_mask = target_mask[:self.max_seq_length]
``` 
这种情况请问下各位可以怎么处理呢

**Comment by no-execution** [comment]
遇到了同样的问题，请问解决了吗？

**Comment by no-execution** [comment]
> 遇到了同样的问题，请问解决了吗？ 但是我的训练还能正常进行

仔细看了下代码，dataset里是先tokenize，并且没有规定truncate参数，所以tokenizer会给出这个warning，但是在后面有限制序列的长度，所以说给到模型的序列长度是ok的，这个warning对实际训练没影响。
