### ISSUE TITLE
Qwen-7B微调后的推理问题

### ISSUE THREAD

**Issue by aiquanpeng** [yangjianxin1/Firefly#94]
![微信图片_20230807154312](https://github.com/yangjianxin1/Firefly/assets/53518009/026104da-dc67-415e-b6c7-dd9c67de1440)

**Comment by aiquanpeng** [comment]
The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation.
A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

**Comment by suwief** [comment]
遇到了同样的问题，请问解决了么

**Comment by FeiWard** [comment]
结果全是乱的，答案都不对，坐等一个解决方案

**Comment by yangjianxin1** [comment]
> The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results. Setting `pad_token_id` to `eos_token_id`:151643 for open-end generation. A decoder-only architecture is being used, but right-padding was detected! For correct generation results, please set `padding_side='left'` when initializing the tokenizer.

这个warning可以不用理会，应该不影响生成。我用这个项目训练的模型，生成结果看起来好像还行
![image](https://github.com/yangjianxin1/Firefly/assets/19970582/826a211e-848f-4ad8-b480-5ecb33ad40e9)

**Comment by Modas-Li** [comment]
same warning:

**Comment by Modas-Li** [comment]
Thank you for your email !您好，你的邮件我已收到，我会尽快给你回复。

**Comment by aiquanpeng** [comment]
训练轮数太大，数据量太少导致，降低训练轮数

**Comment by suwief** [comment]
> 训练轮数太大，数据量太少导致，降低训练轮数

巡礼那轮数设置的1，使用的数据量确实太少，示例中的那些，这个会导致大模型混乱么？

**Comment by qiuwenbogdut** [comment]
遇到了同样的问题, 使用Firefly/script/chat/single_chat.py 脚本 加载最原始的Qwen-7b-chat模型输出也是乱的,
<img width="531" alt="image" src="https://github.com/yangjianxin1/Firefly/assets/17745161/f21b7d7d-ef35-4299-867e-f29495f6faf7">

**Comment by qiuwenbogdut** [comment]
可以参考使用一下下面这段代码, 亲测有效
```

def main():
    model_name = 'Qwen-7B-Chat'
    # model_name = 'YeungNLP/firefly-baichuan-7b'
    # model_name = 'YeungNLP/firefly-ziya-13b'
    # model_name = 'YeungNLP/firefly-bloom-7b1'
    # model_name = 'YeungNLP/firefly-baichuan-7b'
    # model_name = 'YeungNLP/firefly-baichuan-13b'
    # model_name = 'YeungNLP/firefly-bloom-7b1'
    # model_name = 'YeungNLP/firefly-llama-30b'

    max_new_tokens = 500
    top_p = 0.9
    temperature = 0.35
    repetition_penalty = 1.0
    device = 'cuda'
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        trust_remote_code=True,
        low_cpu_mem_usage=True,
        torch_dtype=torch.float16,
        device_map='auto'
    ).to(device).eval()
    tokenizer = AutoTokenizer.from_pretrained(
        model_name,
        trust_remote_code=True,
        # llama不支持fast
        use_fast=False if model.config.model_type == 'llama' else True
    )
    # QWenTokenizer比较特殊，pad_token_id、bos_token_id、eos_token_id均为None。eod_id对应的token为<|endoftext|>
    if tokenizer.__class__.__name__ == 'QWenTokenizer':
        tokenizer.pad_token_id = tokenizer.eod_id
        tokenizer.bos_token_id = tokenizer.eod_id
        tokenizer.eos_token_id = tokenizer.eod_id

    text = input('User：')
    while True:
        text = text.strip()
        # chatglm使用官方的数据组织格式
        if model.config.model_type == 'chatglm':
            text = '[Round 1]\n\n问：{}\n\n答：'.format(text)
            input_ids = tokenizer(text, return_tensors="pt", add_special_tokens=False).input_ids.to(device)
        # 为了兼容qwen-7b，因为其对eos_token进行tokenize，无法得到对应的eos_token_id
        else:
            im_start_tokens = [tokenizer.im_start_id]
            im_end_tokens = [tokenizer.im_end_id]
            nl_tokens = tokenizer.encode("\n")

            def _tokenize_str(role, content):
                return f"{role}\n{content}", tokenizer.encode(
                    role, allowed_special=set()
                ) + nl_tokens + tokenizer.encode(content, allowed_special=set())
            
            system_text, system_tokens_part = _tokenize_str("system", "")

            system_tokens = im_start_tokens + system_tokens_part + im_end_tokens

            context_tokens = []
            context_tokens = system_tokens + context_tokens

            context_tokens += (
                nl_tokens
                + im_start_tokens
                + _tokenize_str("user", text)[1]
                + im_end_tokens
                + nl_tokens
                + im_start_tokens
                + tokenizer.encode("assistant")
                + nl_tokens
            )
            input_ids = torch.tensor([context_tokens]).to(device)

        with torch.no_grad():
            outputs = model.generate(
                input_ids=input_ids, max_new_tokens=max_new_tokens, do_sample=True,
                top_p=top_p, temperature=temperature, repetition_penalty=repetition_penalty,
                eos_token_id=tokenizer.eos_token_id
            )
        outputs = outputs.tolist()[0][len(input_ids[0]):]
        response = tokenizer.decode(outputs)
        response = response.strip().replace(tokenizer.eos_token, "").strip()
        print("Firefly：{}".format(response))
        text = input('User：')


if __name__ == '__main__':
    main()


`

**Comment by yangjianxin1** [comment]
> 遇到了同样的问题, 使用Firefly/script/chat/single_chat.py 脚本 加载最原始的Qwen-7b-chat模型输出也是乱的, <img alt="image" width="531" src="https://user-images.githubusercontent.com/17745161/262266550-f21b7d7d-ef35-4299-867e-f29495f6faf7.png">

因为每个项目或者模型都有其自己的数据组织格式，需要使用官方的推理脚本。firefly里面的推理代码，只支持使用firefly项目训练的模型。

**Comment by qiuwenbogdut** [comment]
> > 遇到了同样的问题, 使用Firefly/script/chat/single_chat.py 脚本 加载最原始的Qwen-7b-chat模型输出也是乱的, <img alt="image" width="531" src="https://user-images.githubusercontent.com/17745161/262266550-f21b7d7d-ef35-4299-867e-f29495f6faf7.png">
> 
> 因为每个项目或者模型都有其自己的数据组织格式，需要使用官方的推理脚本。firefly里面的推理代码，只支持使用firefly项目训练的模型。

感谢解答,谢谢

**Comment by staticTao** [comment]
楼主你好，想请问一下，微调qwen-7b-chat 的时候，我出现了以下的错，请问楼主知道这个是什么错吗？
这个错误出现在启动模型之后。

第一步为正常
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████| 8/8 [00:14<00:00, 1.86s/it]
memory footprint of model: 9.654800474643707 GB
trainable params: 143,130,624 || all params: 4,626,452,480 || trainable%: 3.093744604937561
verify all params of the model
torch.float32 1388449792 0.30011111061925355
torch.uint8 3238002688 0.6998888893807464

第二步就报错了。
verify trainable params the model
torch.float32 143130624 1.0
torch.float32 143130624
2023-09-13 15:15:36.744 | INFO | component.dataset:init:12 - Loading data: ./data/dummy_data.jsonl
2023-09-13 15:15:36.744 | INFO | component.dataset:init:15 - there are 118 data in dataset
2023-09-13 15:15:36.755 | INFO | main:main:207 - *** starting training ***
0%| | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
File "train_qlora.py", line 220, in
main()
File "train_qlora.py", line 208, in main
train_result = trainer.train()
File "/root/anaconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1645, in train
return inner_training_loop(
File "/root/anaconda3/lib/python3.8/site-packages/transformers/trainer.py", line 1916, in _inner_training_loop
for step, inputs in enumerate(epoch_iterator):
File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 628, in next
data = self._next_data()
File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 671, in _next_data
data = self._dataset_fetcher.fetch(index) # may raise StopIteration
File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/root/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 58, in
data = [self.dataset[idx] for idx in possibly_batched_index]
File "/newdisk/tgp/llm_projects/Firefly/component/dataset.py", line 24, in getitem
data = json.loads(data)
File "/root/anaconda3/lib/python3.8/json/init.py", line 357, in loads
return _default_decoder.decode(s)
File "/root/anaconda3/lib/python3.8/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/root/anaconda3/lib/python3.8/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 5 (char 4)
0%| | 0/10 [00:00<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 1759054) of binary: /root/anaconda3/bin/python
Traceback (most recent call last):
File "/root/anaconda3/bin/torchrun", line 8, in
sys.exit(main())
File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/init.py", line 346, in wrapper
return f(*args, **kwargs)
File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
run(args)
File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
elastic_launch(
File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in call
return launch_agent(self._config, self._entrypoint, list(args))
File "/root/anaconda3/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
train_qlora.py FAILED
Failures:
<NO_OTHER_FAILURES>
Root Cause (first observed failure):
[0]:
time : 2023-09-13_15:15:39
host : dell-r7525
rank : 0 (local_rank: 0)
exitcode : 1 (pid: 1759054)
error_file: <N/A>
traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html

**Comment by JOY-SWang** [comment]
还是么用呢
这个是不是灾难性遗忘

**Comment by Vincent-ch99** [comment]
> 还是么用呢 这个是不是灾难性遗忘

灾难性遗忘是没办法回答源域知识，输出的内容都是SFT阶段的语料回答，而不是胡乱回答；上面的问题看起来更像是推理阶段对特殊符eos, pos解析出错导致的，就行前面提到的推理代码中数据组织格式不一致导致的，需要自己debug或者使用源项目推理代码
