### ISSUE TITLE
Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误

### ISSUE THREAD

**Issue by scwunai** [yangjianxin1/Firefly#95]
在4卡RTX A6000 48G服务器上使用firefly微调 Qwen-7B ，Initializing components阶段报如下错误

```shell
2023-08-08 11:21:21.544 | INFO     | __main__:init_components:45 - Initializing components...
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
The model is automatically converting to bf16 for faster inference. If you want to disable the automatic precision, please manually add bf16/fp16/fp32=True to "AutoModelForCausalLM.from_pretrained".
Try importing flash-attention for faster inference...
Warning: import flash_attn rotary fail, please install FlashAttention rotary to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/rotary
Warning: import flash_attn rms_norm fail, please install FlashAttention layer_norm to get higher efficiency https://github.com/Dao-AILab/flash-attention/tree/main/csrc/layer_norm
Warning: import flash_attn fail, please install FlashAttention to get higher efficiency https://github.com/Dao-AILab/flash-attention
[2023-08-08 11:21:22,848] [INFO] [partition_parameters.py:453:__exit__] finished initializing model with 0.69B parameters
Traceback (most recent call last):
  File "train_qwen.py", line 130, in <module>
    main()
  File "train_qwen.py", line 115, in main
    trainer = init_components(args, training_args)
  File "train_qwen.py", line 53, in init_components
    model = AutoModelForCausalLM.from_pretrained(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
Traceback (most recent call last):
  File "train_qwen.py", line 130, in <module>
    main()
  File "train_qwen.py", line 115, in main
    trainer = init_components(args, training_args)
  File "train_qwen.py", line 53, in init_components
    model = AutoModelForCausalLM.from_pretrained(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 844, in __init__
    return model_class.from_pretrained(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    self.transformer = QWenModel(config)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
Traceback (most recent call last):
  File "train_qwen.py", line 130, in <module>
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 617, in __init__
    main()
  File "train_qwen.py", line 115, in main
    [
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 618, in <listcomp>
    model = cls(config, *model_args, **model_kwargs)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    trainer = init_components(args, training_args)
  File "train_qwen.py", line 53, in init_components
        model = AutoModelForCausalLM.from_pretrained(f(module, *args, **kwargs)

  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 844, in __init__
    QWenBlock(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 496, in __init__
    return model_class.from_pretrained(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    self.transformer = QWenModel(config)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    self.attn = QWenAttention(config, layer_number=layer_idx)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 617, in __init__
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 242, in __init__
Traceback (most recent call last):
  File "train_qwen.py", line 130, in <module>
    self.logn_tensor = torch.Tensor(logn_list)[None, :, None, None]
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 245, in new_tensor
    [
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 618, in <listcomp>
    tensor = _orig_torch_empty(0, device=device).new_empty(*args)
TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049
        model = cls(config, *model_args, **model_kwargs)main()

  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
  File "train_qwen.py", line 115, in main
    QWenBlock(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    trainer = init_components(args, training_args)    
f(module, *args, **kwargs)  File "train_qwen.py", line 53, in init_components

      File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 844, in __init__
f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 496, in __init__
    model = AutoModelForCausalLM.from_pretrained(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    self.attn = QWenAttention(config, layer_number=layer_idx)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    self.transformer = QWenModel(config)    
return model_class.from_pretrained(  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper

  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 242, in __init__
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 617, in __init__
    self.logn_tensor = torch.Tensor(logn_list)[None, :, None, None]
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 245, in new_tensor
        tensor = _orig_torch_empty(0, device=device).new_empty(*args)[

  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 618, in <listcomp>
TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049
    QWenBlock(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    model = cls(config, *model_args, **model_kwargs)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 496, in __init__
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 844, in __init__
    self.attn = QWenAttention(config, layer_number=layer_idx)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 242, in __init__
    self.transformer = QWenModel(config)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    self.logn_tensor = torch.Tensor(logn_list)[None, :, None, None]
      File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 245, in new_tensor
f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 617, in __init__
    tensor = _orig_torch_empty(0, device=device).new_empty(*args)
TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049
    [
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 618, in <listcomp>
    QWenBlock(
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 496, in __init__
    self.attn = QWenAttention(config, layer_number=layer_idx)
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "~/.cache/huggingface/modules/transformers_modules/Qwen-7B-Chat/modeling_qwen.py", line 242, in __init__
    self.logn_tensor = torch.Tensor(logn_list)[None, :, None, None]
  File "~/miniconda3/envs/firefly-3.8/lib/python3.8/site-packages/deepspeed/runtime/zero/partition_parameters.py", line 245, in new_tensor
    tensor = _orig_torch_empty(0, device=device).new_empty(*args)
TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049
[2023-08-08 11:21:23,541] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 67781
[2023-08-08 11:21:23,557] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 67782
[2023-08-08 11:21:23,557] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 67783
[2023-08-08 11:21:23,566] [INFO] [launch.py:315:sigkill_handler] Killing subprocess 67803
[2023-08-08 11:21:23,573] [ERROR] [launch.py:321:sigkill_handler] ['~/miniconda3/envs/firefly-3.8/bin/python', '-u', 'train_qwen.py', '--local_rank=3', '--train_args_file', 'train_args/sft_qwen.json'] exits with return code = 1
```

以下为sft.json配置

```shell
{
    "output_dir": "~//firefly-qwen-7b-sft-0808-3epoch",
    "model_name_or_path":"~/Qwen-7B-Chat",
    "deepspeed": "./train_args/ds_z3_config.json",
    "train_file": "~/shuffled_data_0804.jsonl",
    "num_train_epochs": 3,
    "per_device_train_batch_size": 4,
    "gradient_accumulation_steps": 4,
    "learning_rate": 1e-5,
    "max_seq_length": 512,
    "logging_steps": 5,
    "save_steps": 800,
    "save_total_limit": 2,
    "lr_scheduler_type": "cosine",
    "warmup_steps": 3000,

    "gradient_checkpointing": true,
    "disable_tqdm": false,
    "optim": "adamw_hf",
    "seed": 42,
    "fp16": true,
    "report_to": "tensorboard",
    "dataloader_num_workers": 5,
    "save_strategy": "steps",
    "weight_decay": 0,
    "max_grad_norm": 1.0,
    "remove_unused_columns": false
}
```

对于train.py
仅在 setup_everything函数增加    parser.add_argument("--local_rank", type=int, default=0)

```python
def setup_everything():
    parser = argparse.ArgumentParser()
    parser.add_argument("--train_args_file", type=str, default='train_args/sft.json', help="")
    parser.add_argument("--local_rank", type=int, default=0)
    args = parser.parse_args()
    train_args_file = args.train_args_file
    # train_args_file = 'train_args/finetune.json'
    # 读取训练的参数配置
    parser = HfArgumentParser((CustomizedArguments, TrainingArguments))
    # 解析得到自定义参数，以及自带参数
    args, training_args = parser.parse_json_file(json_file=train_args_file)
    # 创建输出目录
    if not os.path.exists(training_args.output_dir):
        os.makedirs(training_args.output_dir)
    logger.add(join(training_args.output_dir, 'train.log'))
    logger.info("train_args:{}".format(training_args))
    # 设置随机种子
    set_seed(training_args.seed)
    return args, training_args
```

数据集采用alpaca-gpt4-data-zh集掺杂私有集合测试训练

使用相同项目微调ChatGLM2没有相关问题，请问该如何解决Qwen-7B的这个问题？非常感谢帮忙

**Comment by pupilshuo** [comment]
遇到了同样的问题

**Comment by DirtyKnightForVi** [comment]
我的和你的类似，在容器上执行命令开启训练，但是return code是-7，更离谱。。。
其中有一段报错是：
caught signal 7 (Bus error: nonexistent physical address)

**Comment by huayicong23** [comment]
我也遇到了这个问题，现在有解决方法了吗

**Comment by DirtyKnightForVi** [comment]
同样的问题，请问楼主解决了吗？

**Comment by huayicong23** [comment]
> 

或者可以在huggingface找到新版的modeling_qwen.py，然后更新一下

**Comment by DirtyKnightForVi** [comment]
> 



> > 
> 
> 或者可以在huggingface找到新版的modeling_qwen.py，然后更新一下

请问你更新之后试成功了吗？我更新之后，使用单卡倒是能加载模型，只是立马报错OOM了。
切换到多卡，就报错：RuntimeError: output tensor must have the same type as input tensor

**Comment by huayicong23** [comment]
我用的deepspeed，参数设置里bf16设置为true就可以正常运行了
---- 回复的原邮件 ----
发件人 DirtyKnightForVi ***@***.***> 发送日期 2023年08月11日 22:45 收件人 yangjianxin1/Firefly ***@***.***> 抄送人 huayicong23 ***@***.***>,
Comment ***@***.***> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95)  

或者可以在huggingface找到新版的modeling_qwen.py，然后更新一下
请问你更新之后试成功了吗？我更新之后，使用单卡倒是能加载模型，只是立马报错OOM了。
 切换到多卡，就报错：RuntimeError: output tensor must have the same type as input tensor

**Comment by DirtyKnightForVi** [comment]
> 我用的deepspeed，参数设置里bf16设置为true就可以正常运行了 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi ***@***.***> 发送日期 2023年08月11日 22:45 收件人 yangjianxin1/Firefly ***@***.***> 抄送人 huayicong23 ***@***.***>, Comment ***@***.***> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 或者可以在huggingface找到新版的modeling_qwen.py，然后更新一下 请问你更新之后试成功了吗？我更新之后，使用单卡倒是能加载模型，只是立马报错OOM了。 切换到多卡，就报错：RuntimeError: output tensor must have the same type as input tensor — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

我的设置和你的一样的。也就是说你多卡没碰到过问题是吗？

**Comment by huayicong23** [comment]
是的，ds的参数和sft.json里面bf16都要设置为true。多卡正常运行。你可以试试按照qwen的requirements安装包，把flash-attention的那些也装上。我按firefly的环境报了几次错，换qwen环境就正常运行了。
---- 回复的原邮件 ----
发件人 DirtyKnightForVi ***@***.***> 发送日期 2023年08月11日 22:57 收件人 yangjianxin1/Firefly ***@***.***> 抄送人 huayicong23 ***@***.***>,
Comment ***@***.***> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95)  

我用的deepspeed，参数设置里bf16设置为true就可以正常运行了 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi @.> 发送日期 2023年08月11日 22:45 收件人 yangjianxin1/Firefly @.> 抄送人 huayicong23 @.>, Comment @.> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 或者可以在huggingface找到新版的modeling_qwen.py，然后更新一下 请问你更新之后试成功了吗？我更新之后，使用单卡倒是能加载模型，只是立马报错OOM了。 切换到多卡，就报错：RuntimeError: output tensor must have the same type as input tensor — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***>
我的设置和你的一样的。也就是说你多卡没碰到过问题是吗？

**Comment by DirtyKnightForVi** [comment]
> 是的，ds的参数和sft.json里面bf16都要设置为true。多卡正常运行。你可以试试按照qwen的requirements安装包，把flash-attention的那些也装上。我按firefly的环境报了几次错，换qwen环境就正常运行了。 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi ***@***.***> 发送日期 2023年08月11日 22:57 收件人 yangjianxin1/Firefly ***@***.***> 抄送人 huayicong23 ***@***.***>, Comment ***@***.***> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 我用的deepspeed，参数设置里bf16设置为true就可以正常运行了 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi @.> 发送日期 2023年08月11日 22:45 收件人 yangjianxin1/Firefly @.> 抄送人 huayicong23 @.>, Comment @.> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 或者可以在huggingface找到新版的modeling_qwen.py，然后更新一下 请问你更新之后试成功了吗？我更新之后，使用单卡倒是能加载模型，只是立马报错OOM了。 切换到多卡，就报错：RuntimeError: output tensor must have the same type as input tensor — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.***> 我的设置和你的一样的。也就是说你多卡没碰到过问题是吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

bf16吗？我看你的贴出来的sft.json是fp16。抱歉，初次使用deepspeed，踩坑中。
抱着试一试的态度，我把两个json文件中的fp16的相关值都设置成了true，但还是没作用。环境是OK的。

**Comment by huayicong23** [comment]
我刚刚又试了一下，firefly环境报错，错误与flash-attn相关，大概是版本问题。我用qwen环境，报的两个错和你一样，分别通过更新modeling_qwen和把fp16都替换为bf16并且设置为true，就能正常运行了。错误原因和对应解决方法之间的关联我还不太清楚，只算是摸索出了一条能运行的路子
---- 回复的原邮件 ----
发件人 DirtyKnightForVi ***@***.***> 发送日期 2023年08月12日 00:13 收件人 yangjianxin1/Firefly ***@***.***> 抄送人 langtourist ***@***.***>,
Comment ***@***.***> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95)  

是的，ds的参数和sft.json里面bf16都要设置为true。多卡正常运行。你可以试试按照qwen的requirements安装包，把flash-attention的那些也装上。我按firefly的环境报了几次错，换qwen环境就正常运行了。 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi @.> 发送日期 2023年08月11日 22:57 收件人 yangjianxin1/Firefly @.> 抄送人 huayicong23 @.>, Comment @.> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 我用的deepspeed，参数设置里bf16设置为true就可以正常运行了 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi @.> 发送日期 2023年08月11日 22:45 收件人 yangjianxin1/Firefly @.> 抄送人 huayicong23 @.>, Comment @.> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 或者可以在huggingface找到新版的modeling_qwen.py，然后更新一下 请问你更新之后试成功了吗？我更新之后，使用单卡倒是能加载模型，只是立马报错OOM了。 切换到多卡，就报错：RuntimeError: output tensor must have the same type as input tensor — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 我的设置和你的一样的。也就是说你多卡没碰到过问题是吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.>
bf16吗？我看你的贴出来的sft.json是fp16。抱歉，初次使用deepspeed，踩坑中。
 抱着试一试的态度，我把两个json文件中的fp16的相关值都设置成了true，但还是没作用。环境是OK的。

**Comment by DirtyKnightForVi** [comment]
> 我刚刚又试了一下，firefly环境报错，错误与flash-attn相关，大概是版本问题。我用qwen环境，报的两个错和你一样，分别通过更新modeling_qwen和把fp16都替换为bf16并且设置为true，就能正常运行了。错误原因和对应解决方法之间的关联我还不太清楚，只算是摸索出了一条能运行的路子 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi ***@***.***> 发送日期 2023年08月12日 00:13 收件人 yangjianxin1/Firefly ***@***.***> 抄送人 langtourist ***@***.***>, Comment ***@***.***> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 是的，ds的参数和sft.json里面bf16都要设置为true。多卡正常运行。你可以试试按照qwen的requirements安装包，把flash-attention的那些也装上。我按firefly的环境报了几次错，换qwen环境就正常运行了。 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi @.> 发送日期 2023年08月11日 22:57 收件人 yangjianxin1/Firefly @.> 抄送人 huayicong23 @.>, Comment @.> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 我用的deepspeed，参数设置里bf16设置为true就可以正常运行了 ---- 回复的原邮件 ---- 发件人 DirtyKnightForVi @.> 发送日期 2023年08月11日 22:45 收件人 yangjianxin1/Firefly @.> 抄送人 huayicong23 @.>, Comment @.> 主题 Re: [yangjianxin1/Firefly] Qwen-7B 全参数 SFT Initializing components阶段报 TypeError: new_empty(): argument 'size' must be tuple of SymInts, but found element of type float at pos 2049 的错误 (Issue #95) 或者可以在huggingface找到新版的modeling_qwen.py，然后更新一下 请问你更新之后试成功了吗？我更新之后，使用单卡倒是能加载模型，只是立马报错OOM了。 切换到多卡，就报错：RuntimeError: output tensor must have the same type as input tensor — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> 我的设置和你的一样的。也就是说你多卡没碰到过问题是吗？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: @.> bf16吗？我看你的贴出来的sft.json是fp16。抱歉，初次使用deepspeed，踩坑中。 抱着试一试的态度，我把两个json文件中的fp16的相关值都设置成了true，但还是没作用。环境是OK的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

谢谢你的回复。能烦请把两个json的内容贴一下吗？我这是一个内网的机器，着实没法贴出我这边的配置QAQ

**Comment by huayicong23** [comment]
> 

![image](https://github.com/yangjianxin1/Firefly/assets/137380404/b44462a3-2603-4f15-bafe-56d40a9584a9)
这是ds bf16的配置，其他参数都没改
![image](https://github.com/yangjianxin1/Firefly/assets/137380404/6a4d27fe-eba4-4cd6-9265-fa3daf335c34)
这是sft.json的配置

**Comment by huayicong23** [comment]
@DirtyKnightForVi

**Comment by DirtyKnightForVi** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/137380404/260064746-b44462a3-2603-4f15-bafe-56d40a9584a9.png) 这是ds bf16的配置，其他参数都没改 ![image](https://user-images.githubusercontent.com/137380404/260065073-6a4d27fe-eba4-4cd6-9265-fa3daf335c34.png) 这是sft.json的配置

好的，谢谢，我这边的问题也解决了，只是直接OOM了哈哈。四卡的A100-40G没撑住。看来只能lora了
