### ISSUE TITLE
Qwen-7B-chat lora微调后推理报错

### ISSUE THREAD

**Issue by sunzhaowei** [yangjianxin1/Firefly#97]
推理之前我加了以下代码：
model.generation_config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True)

但是model.chat调用时报下面的错误
GenerationConfig object has no attribute 'chat_format'

**Comment by samsha1971** [comment]
微调是没遇到以下错误？
` File "/home/sam/.cache/huggingface/modules/transformers_modules/Qwen/Qwen-7B/2da968fcdde29dde4a7005cfad9ca92014f64c74/modeling_qwen.py", line 130, in forward
    assert all((i.dtype in [torch.float16, torch.bfloat16] for i in (q, k, v)))
AssertionError
  0%|                                                                                  | 0/2398 [00:00<?, ?it/s]
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 32007) of binary: /home/sam/anaconda3/envs/finetuning/bin/python
Traceback (most recent call last):
  File "/home/sam/anaconda3/envs/finetuning/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sam/anaconda3/envs/finetuning/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/sam/anaconda3/envs/finetuning/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/sam/anaconda3/envs/finetuning/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/sam/anaconda3/envs/finetuning/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sam/anaconda3/envs/finetuning/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_qlora.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-08-16_15:19:10
  host      : sam-MS-7D91
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 32007)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`

**Comment by yangjianxin1** [comment]
使用的是否是项目script/chat里面的推理脚本

**Comment by VitoUnderwood** [comment]
> 推理之前我加了以下代码： model.generation_config = GenerationConfig.from_pretrained(model_path, trust_remote_code=True)
> 
> 但是model.chat调用时报下面的错误 GenerationConfig object has no attribute 'chat_format'

merge过程的问题，把config和generation config同步一下就行

**Comment by samsha1971** [comment]
model.generation_config = GenerationConfig.from_pretrained(model_name, trust_remote_code=True)
model.chat(tokenizer, question, history, generation_config=model.generation_config)

**Comment by VitoUnderwood** [comment]
邮件已收到，我会尽快回复。

**Comment by wangschang** [comment]
请问如何同步
