### ISSUE TITLE
单卡qlora baichuan-7b报错：torch.distributed.elastic.multiprocessing.errors.ChildFailedError

### ISSUE THREAD

**Issue by nonelight** [yangjianxin1/Firefly#98]
**错误描述：**
按照文档提示搭完系统，根据公众号https://mp.weixin.qq.com/s/ZBY6kbogHjbCQvZBzNEqag文章进行Qlora预训练，双卡命令如下
`torchrun --nproc_per_node=2 train_qlora.py --train_args_file train_args/qlora/baichuan-7b-sft-qlora.json`
双卡报错后试验单卡，
`CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node=1 train_qlora.py --train_args_file train_args/qlora/baichuan-7b-sft-qlora.json`
都报了同样的错误。但是使用ide在train_qlora.py中的直接执行main，成功完成
**主要软硬件配置信息：**
双卡A5000 24g,
cuda 11.7,
python 3.10
torch 1.13.0,
bitsandbytes 0.39.0
deepspeed 0.9.5
peft 0.5.0.dev0
accelerate 0.22.0.dev0
transformers                  4.32.0.dev0
transformers-stream-generator 0.0.4
**错误日志如下：**
Traceback (most recent call last):
  File "/data1/Firefly/train_qlora.py", line 212, in <module>
    main()
  File "/data1/Firefly/train_qlora.py", line 200, in main
    train_result = trainer.train()
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/transformers/trainer.py", line 1534, in train
    return inner_training_loop(
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/transformers/trainer.py", line 1654, in _inner_training_loop
    model, self.optimizer = self.accelerator.prepare(self.model, self.optimizer)
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/accelerator.py", line 1260, in prepare
    result = tuple(
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/accelerator.py", line 1261, in <genexpr>
    self._prepare_one(obj, first_pass=True, device_placement=d) for obj, d in zip(args, device_placement)
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/accelerator.py", line 1084, in _prepare_one
    return self.prepare_model(obj, device_placement=device_placement)
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/accelerate/accelerator.py", line 1329, in prepare_model
    raise ValueError(
ValueError: You can't train a model that has been loaded with `device_map='auto'` in any distributed mode. Please rerun your script specifying `--num_processes=1` or by launching with `python {{myscript.py}}`.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 527527) of binary: /home/app/miniconda3/envs/firefly/bin/python
Traceback (most recent call last):
  File "/home/app/miniconda3/envs/firefly/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.0', 'console_scripts', 'torchrun')())
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/app/miniconda3/envs/firefly/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError

望回复

**Comment by nonelight** [comment]
自问自答下，clone最新版本的代码后，不要安装requirements.txt
执行conda env create -f environment.yml -n new_env_name。按照作者测试时的版本安装环境
我的问题是accelerate包版本高了
此问题技术

**Comment by nonelight** [comment]
> @nonelight zhe ge这个是我执行了conda env create -f environment.yml -n new_env_name的报错，我拉取的是最新代码 <img alt="image" width="1906" src="https://user-images.githubusercontent.com/28706321/260209378-b30afebb-e02d-41f5-abc9-9a3d96b0946b.png">

那你就按照这个文件里面所描述的各个包的版本，自行pip安装即可。
